version: '3.8'

services:
  efilibrary-frontend-staging:
    container_name: efilibrary-frontend-staging
    image: ${IMAGE_NAME}
    stdin_open: true
    tty: true
    build:
      args:
        REACT_APP_BACKEND_URL: 'https://backend-staging-efilibrary.jrdie.nl'
      context: ./
      dockerfile: node.Dockerfile
    environment:
      PORT: '3000'
      REACT_APP_BACKEND_URL: 'https://backend-staging-efilibrary.jrdie.nl'
    volumes:
      - ./src:/app/src
      - ./robot:/app/robot
      - ./public:/app/public:ro
    networks:
      - efilibrary

networks:
  efilibrary:
    external: true
