version: '3.8'

services:
  frontend:
    container_name: docker-robot
    image: docker-robot
    stdin_open: true
    tty: true   
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./robot:/app/robot
      - ./public:/app/public:ro
    ports:
      - "3000:3000"