version: '3.8'

services:
  efilibrary-frontend-staging:
    container_name: efilibrary-frontend-staging
    image: ${IMAGE_NAME}
    stdin_open: true
    tty: true
    build:
      args:
        REACT_APP_BACKEND_URL: "https://host.docker.internal:3002"
      context: ./
      dockerfile: node.Dockerfile
    environment:
      PORT: "3000"
      REACT_APP_BACKEND_URL: "https://host.docker.internal:3002"
      TESTVAR: ${ENV_TEST}
    volumes:
      - ./src:/app/src
      - ./robot:/app/robot
      - ./public:/app/public:ro
    networks:
      - efilibrary

networks:
  efilibrary:
    external: true
