version: '3.8'
# Used for deploy-staging.yml worflow to push image to ghcr.io
services:
  efilibrary-frontend-nginx:
    container_name: efilibrary-frontend-nginx
    image: ${IMAGE_NAME}
    stdin_open: true 
    tty: true 
    build:
      args:
        REACT_APP_BACKEND_URL: 'http://efilibrary-backend:3002' # This is the name of the backend service in the docker-compose file in staging
      context: ./
      dockerfile: Dockerfile.staging
    ports:
      - '3000:80' # 3000 is the port that the container exposes, 80 is the port that the app runs on
