version: '3.8'
# Backend must be running on for this to work
# This service builds and starts frontend and runs the tests in docker and
# Closes the frontend container when tests are done
services:
  docker-robot:
    shm_size: 2gb
    container_name: docker-robot
    image: docker-robot
    stdin_open: true
    tty: true
    command: npm run startserverandtest
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./robot:/app/robot
      - ./public:/app/public:ro
    ports:
      - '3000:3000'
