version: '3.8'

services:
  efilibrary-frontend-local:
    container_name: efilibrary-frontend-local
    image: efilibrary-frontend-local
    shm_size: 2gb
    stdin_open: true
    tty: true
    command: npm run start
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public:ro
      - ./robot:/app/robot
    ports:
      - '3000:3000'
