version: '3.3'

services:
  efilibrary-backend:
    image: ghcr.io/libraryprojectgroup/library-project-backend:alpine

    #    stdin_open: true

    environment:
      DATABASE_SERVER: ${DATABASE_SERVER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      OIDC_AUTH_BACKLINK_URL: ${OIDC_AUTH_BACKLINK_URL}
      OIDC_AUTH_REDIRECT_URL: ${OIDC_AUTH_REDIRECT_URL}
      PORT: 3002
    volumes:
      - sql:/app/sql/.
    ports:
      - 3002:3002
    networks:
      - efilibrary-network  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3  

  efilibrary-mysql:
    image: mysql
    volumes:
      - sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - 3306:3306

    expose:
      - 3306
    networks:
      - efilibrary-network

networks:
  efilibrary-network:
volumes:
  sql: