name: Deploy frontend to staging

on:
  push:
    branches: ['development', 'gh-actions', s23-docker-compose-tests]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/libraryprojectgroup/library-project-frontend:nginx

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build image
        #run docker-compose -f docker-compose-staging.yml build || This builds frontend image using node.Dockerfile
        run: docker-compose -f docker-compose-nginx.yml build  # This builds smaller image with ngingx using Dockerfile.staging

      - name: Log in to the container registry
        uses: docker/login-action@v2
        
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        #run docker-compose -f docker-compose-staging.yml
        run: docker-compose -f docker-compose-nginx.yml push