name: Deploy frontend to staging

on:
  push:
    branches: ['development', 'gh-actions']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/libraryprojectgroup/library-project-frontend:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build image
        run: docker-compose -f docker-compose-staging.yml build
      - name: Log in to the container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: docker-compose -f docker-compose-staging.yml push
      
