name: Build backend and frontend containers and run robot tests for frontend with Docker

on:
  push:
    branches: ['development', s23-docker-compose-tests]
  pull_request:
    branches: ['development']

env:
  DATABASE_SERVER: ${{ secrets.DATABASE_SERVER }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  DATABASE_USER: ${{ secrets.MYSQL_USER }}
  DATABASE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  OIDC_AUTH_BACKLINK_URL: ${{ secrets.OIDC_AUTH_BACKLINK_URL }}
  OIDC_AUTH_REDIRECT_URL: ${{ secrets.OIDC_AUTH_REDIRECT_URL }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  COMPOSE_PROJECT_NAME: ${{ secrets.COMPOSE_PROJECT_NAME }}
  TESTUSERNAME: ${{ secrets.REACT_APP_TEST_USERNAME }}
  TESTUSERNAME2: ${{ secrets.REACT_APP_TEST_USERNAME2 }}
  TESTPASSWORD: ${{ secrets.REACT_APP_TEST_PASSWORD }}
  TESTPASSWORD2: ${{ secrets.REACT_APP_TEST_PASSWORD2 }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "DATABASE_SERVER=${{ secrets.DATABASE_SERVER }}" >> .env
          echo "DATABASE_NAME=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "DATABASE_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "OIDC_AUTH_BACKLINK_URL=${{ secrets.OIDC_AUTH_BACKLINK_URL }}" >> .env
          echo "OIDC_AUTH_REDIRECT_URL=${{ secrets.OIDC_AUTH_REDIRECT_URL }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
          echo "COMPOSE_PROJECT_NAME=${{ env.COMPOSE_PROJECT_NAME }}" >> .env
          echo "TESTUSERNAME=${{ secrets.REACT_APP_TEST_USERNAME }}" >> .env
          echo "TESTUSERNAME2=${{ secrets.REACT_APP_TEST_USERNAME }}" >> .env
          echo "TESTPASSWORD=${{ secrets.REACT_APP_TEST_PASSWORD }}" >> .env
          echo "TESTPASSWORD2=${{ secrets.REACT_APP_TEST_PASSWORD2 }}" >> .env
          echo "REACT_APP_BACKEND_URL=${{ secrets.BACKEND_URL }}" >> .env

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_ACCES_TEST_USER}} #My personal access token so not usable for long term
          password: ${{ secrets.GHCR_ACCES_TEST_TOKEN }} 
            
      - name: Build and run backend containers
        run: docker-compose -f docker-compose-start-backend.yml up -d
      
      - name: Start frontend
        run: docker-compose -f docker-compose-start-frontend.yml up -d

      - name: Check Port 3000 Usage
        run: |
          netstat -tuln | grep 3000 || echo "Port 3000 is available"   

      - name: Run tests
        run:  npm run dockertests

      - name: Clean up
        if: always()
        run: |
          docker-compose -f docker-compose-start-frontend.yml down
          docker-compose -f docker-compose-start-backend.yml down
          
