name: Node.js CI

on:
  push:
    branches: ['development', s23-docker-compose-tests]
  pull_request:
    branches: ['development']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "DATABASE_SERVER=${{ env.DATABASE_SERVER }}" >> .env
          echo "DATABASE_NAME=${{ env.DATABASE_NAME }}" >> .env
          echo "DATABASE_USER=${{ env.DATABASE_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ env.DATABASE_PASSWORD }}" >> .env
          echo "OIDC_AUTH_BACKLINK_URL=${{ env.OIDC_AUTH_BACKLINK_URL }}" >> .env
          echo "OIDC_AUTH_REDIRECT_URL=${{ env.OIDC_AUTH_REDIRECT_URL }}" >> .env
          echo "MYSQL_DATABASE=${{ env.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ env.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ env.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{ env.MYSQL_ROOT_PASSWORD }}" >> .env

      - name: Log in to the container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}    

      - name: Build and run containers
        run: docker-compose -f docker-compose-test-with-backend.yml up --build -d

      - name: Clean up
        if: always()
        run: docker-compose -f docker-compose-test-with-backend.yml down
